In [2]:
# Importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# import os

# print("Current folder:")
# print(os.getcwd())

# print("\nFiles inside data/raw:")
# print(os.listdir("../data/raw"))

In [4]:
# Loading Dataset
df = pd.read_csv("../data/raw/telco_customer_churn.csv")

In [5]:
# 1st 5 rows of the dataset
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [6]:
# Checking Dimension
df.shape

(7043, 21)

In [7]:
# Analyzing columns
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [8]:
# Checking data types
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [9]:
# Checking missing values
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [25]:
# Finding blank TotalCharges
df[df["TotalCharges"].str.strip() == ""]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,,No

In [26]:
# Counting blank TotalCharges
(df["TotalCharges"].str.strip() == "").sum()

np.int64(11)

In [27]:
# Checking duplicate customers
df.duplicated().sum()

np.int64(0)

In [28]:
df["customerID"].duplicated().sum()

np.int64(0)

In [29]:
# Looking at Unique values
for column in df.columns:
    print(column)
    print(df[column].unique())
    print("-" * 50)

customerID
<StringArray>
['7590-VHVEG', '5575-GNVDE', '3668-QPYBK', '7795-CFOCW', '9237-HQITU',
 '9305-CDSKC', '1452-KIOVK', '6713-OKOMC', '7892-POOKP', '6388-TABGU',
 ...
 '9767-FFLEM', '0639-TSIQW', '8456-QDAVC', '7750-EYXWZ', '2569-WGERO',
 '6840-RESVB', '2234-XADUH', '4801-JZAZL', '8361-LTMKD', '3186-AJIEK']
Length: 7043, dtype: str
--------------------------------------------------
gender
<StringArray>
['Female', 'Male']
Length: 2, dtype: str
--------------------------------------------------
SeniorCitizen
[0 1]
--------------------------------------------------
Partner
<StringArray>
['Yes', 'No']
Length: 2, dtype: str
--------------------------------------------------
Dependents
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
--------------------------------------------------
tenure
[ 1 34  2 45  8 22 10 28 62 13 16 58 49 25 69 52 71 21 12 30 47 72 17 27
  5 46 11 70 63 43 15 60 18 66  9  3 31 50 64 56  7 42 35 48 29 65 38 68
 32 55 37 36 41  6  4 33 67 23 57 61 14 20 53 40 59 24 44 19 54 51 26  0
 39]
--------------------------------------------------
PhoneService
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
--------------------------------------------------
MultipleLines
<StringArray>
['No phone service', 'No', 'Yes']
Length: 3, dtype: str
--------------------------------------------------
InternetService
<StringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str
--------------------------------------------------
OnlineSecurity
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
--------------------------------------------------
OnlineBackup
<StringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str
--------------------------------------------------
DeviceProtection
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
--------------------------------------------------
TechSupport
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
--------------------------------------------------
StreamingTV
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
--------------------------------------------------
StreamingMovies
<StringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
--------------------------------------------------
Contract
<StringArray>
['Month-to-month', 'One year', 'Two year']
Length: 3, dtype: str
--------------------------------------------------
PaperlessBilling
<StringArray>
['Yes', 'No']
Length: 2, dtype: str
--------------------------------------------------
PaymentMethod
<StringArray>
[         'Electronic check',              'Mailed check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str
--------------------------------------------------
MonthlyCharges
[29.85 56.95 53.85 ... 63.1  44.2  78.7 ]
--------------------------------------------------
TotalCharges
<StringArray>
[  '29.85',  '1889.5',  '108.15', '1840.75',  '151.65',   '820.5',  '1949.4',
   '301.9', '3046.05', '3487.95',
 ...
 '2625.25', '6886.25',  '1495.1',   '743.3',  '1419.4',  '1990.5',  '7362.9',
  '346.45',   '306.6',  '6844.5']
Length: 6531, dtype: str
--------------------------------------------------
Churn
<StringArray>
['No', 'Yes']
Length: 2, dtype: str
--------------------------------------------------

In [30]:
# Examine churn distribution
df["Churn"].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [31]:
df["Churn"].value_counts(normalize=True) * 100

Churn
No     73.463013
Yes    26.536987
Name: proportion, dtype: float64

In [32]:
# Basic statistical summary

df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [33]:
#  Basic statistical summary for categorical columns
df.describe(include="object")

C:\Users\Dell\AppData\Local\Temp\ipykernel_21392\932501761.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,customerID,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,TotalCharges,Churn
count,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043
unique,7043,2,2,2,2,3,3,3,3,3,3,3,3,3,2,4,6531,2
top,7590-VHVEG,Male,No,No,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,20.2,No
freq,1,3555,3641,4933,6361,3390,3096,3498,3088,3095,3473,2810,2785,3875,4171,2365,11,5174

In [34]:
# Creating a quick dataset report
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate customer IDs:", df["customerID"].duplicated().sum())

print("\nChurn distribution:")
print(df["Churn"].value_counts())

print("\nChurn percentage:")
print(df["Churn"].value_counts(normalize=True) * 100)

Rows: 7043
Columns: 21
Duplicate rows: 0
Duplicate customer IDs: 0

Churn distribution:
Churn
No     5174
Yes    1869
Name: count, dtype: int64

Churn percentage:
Churn
No     73.463013
Yes    26.536987
Name: proportion, dtype: float64

**Defining our ML problem**

In [35]:
# # Problem Statement

# The objective of this project is to build a machine learning
# system capable of predicting whether a telecom customer is
# likely to churn.

# The system will provide:

# 1. Churn prediction
# 2. Churn probability
# 3. Feature-level explanations
# 4. Customer risk segmentation
# 5. AI-generated explanations
# 6. Retention recommendations

# Target Variable:

# Churn

# Problem Type:

# Binary Classification

# Churn = 1 → Customer leaves
# Churn = 0 → Customer stays

**Defining business questions**

In [36]:
# ## Business Questions

# 1. What percentage of customers churn?

# 2. Does contract type affect churn?

# 3. Are new customers more likely to churn?

# 4. Do higher monthly charges increase churn?

# 5. Does internet service affect churn?

# 6. Does technical support reduce churn?

# 7. Which payment methods are associated with higher churn?

# 8. What characteristics define high-risk customers?

# 9. Which customers should receive retention offers?

# 10. Why did the ML model classify a particular customer as high risk?

# Phase 2 : Data Cleaning + Exploratory Data Analysis

In [37]:
# Make a working copy
df_clean = df.copy()

In [ ]:
# Checking column names
df_clean.columns.tolist()

['customerID',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn']

In [40]:
df_clean.columns = (
    df_clean.columns
    .str.strip()
    .str.lower()
)

In [41]:
df_clean.columns

Index(['customerid', 'gender', 'seniorcitizen', 'partner', 'dependents',
       'tenure', 'phoneservice', 'multiplelines', 'internetservice',
       'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
       'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling',
       'paymentmethod', 'monthlycharges', 'totalcharges', 'churn'],
      dtype='str')

In [42]:
# Fix TotalCharges
df_clean["totalcharges"].dtype

In [43]:
(df_clean["totalcharges"].str.strip() == "").sum()

np.int64(11)

In [44]:
# Let's inspect 
df_clean[
    df_clean["totalcharges"].str.strip() == ""
][["customerid", "tenure", "monthlycharges", "totalcharges"]]

      customerid  tenure  monthlycharges totalcharges
488   4472-LVYGI       0           52.55
753   3115-CZMZD       0           20.25
936   5709-LVOEQ       0           80.85
1082  4367-NUYAO       0           25.75
1340  1371-DWPAZ       0           56.05
3331  7644-OMVMY       0           19.85
3826  3213-VVOLG       0           25.35
4380  2520-SGTTA       0           20.00
5218  2923-ARZLG       0           19.70
6670  4075-WKNIU       0           73.35
6754  2775-SEFEE       0           61.90

In [45]:
# Convert TotalCharges to numeric
df_clean["totalcharges"] = pd.to_numeric(
    df_clean["totalcharges"],
    errors="coerce"
)

In [46]:
df_clean["totalcharges"].isnull().sum()

np.int64(11)

In [47]:
df_clean["totalcharges"] = df_clean["totalcharges"].fillna(0)

In [48]:
df_clean["totalcharges"].isnull().sum()

np.int64(0)

In [49]:
# check datatypes
df_clean["totalcharges"].dtype

dtype('float64')

In [ ]:
# 
df_clean.dropna()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

In [51]:
# Check duplicates
df_clean.duplicated().sum()

np.int64(0)

In [52]:
df_clean["customerid"].duplicated().sum()

np.int64(0)

In [53]:
# Check categorical values
categorical_cols = df_clean.select_dtypes(
    include="object"
).columns

categorical_cols

C:\Users\Dell\AppData\Local\Temp\ipykernel_21392\2719024123.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df_clean.select_dtypes(

Index(['customerid', 'gender', 'partner', 'dependents', 'phoneservice',
       'multiplelines', 'internetservice', 'onlinesecurity', 'onlinebackup',
       'deviceprotection', 'techsupport', 'streamingtv', 'streamingmovies',
       'contract', 'paperlessbilling', 'paymentmethod', 'churn'],
      dtype='str')

In [54]:
for col in categorical_cols:
    print(f"\n{col}")
    print(df_clean[col].value_counts())

customerid
customerid
7590-VHVEG    1
5575-GNVDE    1
3668-QPYBK    1
7795-CFOCW    1
9237-HQITU    1
             ..
6840-RESVB    1
2234-XADUH    1
4801-JZAZL    1
8361-LTMKD    1
3186-AJIEK    1
Name: count, Length: 7043, dtype: int64

gender
gender
Male      3555
Female    3488
Name: count, dtype: int64

partner
partner
No     3641
Yes    3402
Name: count, dtype: int64

dependents
dependents
No     4933
Yes    2110
Name: count, dtype: int64

phoneservice
phoneservice
Yes    6361
No      682
Name: count, dtype: int64

multiplelines
multiplelines
No                  3390
Yes                 2971
No phone service     682
Name: count, dtype: int64

internetservice
internetservice
Fiber optic    3096
DSL            2421
No             1526
Name: count, dtype: int64

onlinesecurity
onlinesecurity
No                     3498
Yes                    2019
No internet service    1526
Name: count, dtype: int64

onlinebackup
onlinebackup
No                     3088
Yes                    2429
No internet service    1526
Name: count, dtype: int64

deviceprotection
deviceprotection
No                     3095
Yes                    2422
No internet service    1526
Name: count, dtype: int64

techsupport
techsupport
No                     3473
Yes                    2044
No internet service    1526
Name: count, dtype: int64

streamingtv
streamingtv
No                     2810
Yes                    2707
No internet service    1526
Name: count, dtype: int64

streamingmovies
streamingmovies
No                     2785
Yes                    2732
No internet service    1526
Name: count, dtype: int64

contract
contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

paperlessbilling
paperlessbilling
Yes    4171
No     2872
Name: count, dtype: int64

paymentmethod
paymentmethod
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

churn
churn
No     5174
Yes    1869
Name: count, dtype: int64

In [55]:
# Convert churn target
df_clean["churn_flag"] = df_clean["churn"].map({
    "Yes": 1,
    "No": 0
})

In [56]:
df_clean[["churn", "churn_flag"]].head()

  churn  churn_flag
0    No           0
1    No           0
2   Yes           1
3    No           0
4   Yes           1

In [57]:
# Check numeric columns
df_clean.select_dtypes(include=np.number).columns

Index(['seniorcitizen', 'tenure', 'monthlycharges', 'totalcharges',
       'churn_flag'],
      dtype='str')

In [58]:
# Check invalid ranges
df_clean["tenure"].describe()

count    7043.000000
mean       32.371149
std        24.559481
min         0.000000
25%         9.000000
50%        29.000000
75%        55.000000
max        72.000000
Name: tenure, dtype: float64

In [59]:
df_clean[df_clean["tenure"] < 0]

Empty DataFrame
Columns: [customerid, gender, seniorcitizen, partner, dependents, tenure, phoneservice, multiplelines, internetservice, onlinesecurity, onlinebackup, deviceprotection, techsupport, streamingtv, streamingmovies, contract, paperlessbilling, paymentmethod, monthlycharges, totalcharges, churn, churn_flag]
Index: []

[0 rows x 22 columns]

In [60]:
# Monthly charges
df_clean["monthlycharges"].describe()

count    7043.000000
mean       64.761692
std        30.090047
min        18.250000
25%        35.500000
50%        70.350000
75%        89.850000
max       118.750000
Name: monthlycharges, dtype: float64

In [61]:
df_clean[df_clean["monthlycharges"] < 0]

Empty DataFrame
Columns: [customerid, gender, seniorcitizen, partner, dependents, tenure, phoneservice, multiplelines, internetservice, onlinesecurity, onlinebackup, deviceprotection, techsupport, streamingtv, streamingmovies, contract, paperlessbilling, paymentmethod, monthlycharges, totalcharges, churn, churn_flag]
Index: []

[0 rows x 22 columns]

In [62]:
df_clean["totalcharges"].describe()

count    7043.000000
mean     2279.734304
std      2266.794470
min         0.000000
25%       398.550000
50%      1394.550000
75%      3786.600000
max      8684.800000
Name: totalcharges, dtype: float64

In [63]:
df_clean[df_clean["totalcharges"] < 0]

Empty DataFrame
Columns: [customerid, gender, seniorcitizen, partner, dependents, tenure, phoneservice, multiplelines, internetservice, onlinesecurity, onlinebackup, deviceprotection, techsupport, streamingtv, streamingmovies, contract, paperlessbilling, paymentmethod, monthlycharges, totalcharges, churn, churn_flag]
Index: []

[0 rows x 22 columns]

In [64]:
# Check unique values again
for col in df_clean.columns:
    print(
        col,
        "=>",
        df_clean[col].nunique()
    )

customerid => 7043
gender => 2
seniorcitizen => 2
partner => 2
dependents => 2
tenure => 73
phoneservice => 2
multiplelines => 3
internetservice => 3
onlinesecurity => 3
onlinebackup => 3
deviceprotection => 3
techsupport => 3
streamingtv => 3
streamingmovies => 3
contract => 3
paperlessbilling => 2
paymentmethod => 4
monthlycharges => 1585
totalcharges => 6531
churn => 2
churn_flag => 2

In [65]:
# Save cleaned data
df_clean.to_csv(
    "../data/processed/telco_customer_churn_clean.csv",
    index=False
)